import { describe, expect, test } from "bun:test";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { compileSource } from "../src/compiler";
import { materializeSource } from "../src/materialize";
import { projectManifest } from "../src/manifest";
import { planSource } from "../src/plan";

function fixture(name: string): string {
  return readFileSync(new URL(`../fixtures/compiler/${name}`, import.meta.url), "utf8");
}

function compileFixture(name: string) {
  return compileSource(fixture(name), { path: `fixtures/compiler/${name}` });
}

describe("OpenProse compiler", () => {
  test("compiles a single service to IR", () => {
    const ir = compileFixture("hello.prose.md");

    expect(ir.ir_version).toBe("0.1");
    expect(ir.package.name).toBe("hello");
    expect(ir.components).toHaveLength(1);
    expect(ir.components[0].kind).toBe("service");
    expect(ir.components[0].ports.ensures[0]).toMatchObject({
      name: "message",
      type: "Markdown<Greeting>",
      direction: "output",
      required: true,
    });
    expect(ir.components[0].effects[0]).toMatchObject({ kind: "pure" });
    expect(ir.diagnostics).toEqual([]);
  });

  test("builds exact graph edges for inline pipeline components", () => {
    const ir = compileFixture("pipeline.prose.md");
    const edges = ir.graph.edges.map(
      (edge) =>
        `${edge.from.component}.${edge.from.port}->${edge.to.component}.${edge.to.port}`,
    );

    expect(ir.components.map((component) => component.id)).toEqual([
      "content-pipeline",
      "review",
      "fact-check",
      "polish",
    ]);
    expect(edges).toContain("$caller.draft->review.draft");
    expect(edges).toContain("$caller.draft->fact-check.draft");
    expect(edges).toContain("$caller.draft->polish.draft");
    expect(edges).toContain("review.feedback->polish.feedback");
    expect(edges).toContain("fact-check.claims->polish.claims");
    expect(edges).toContain("polish.final->$return.final");
    expect(ir.diagnostics).toEqual([]);
  });

  test("parses typed ports, run inputs, effects, access, environment, and execution", () => {
    const ir = compileFixture("typed-effects.prose.md");
    const program = ir.components[0];

    expect(program.ports.requires.map((port) => [port.name, port.type])).toEqual([
      ["company", "CompanyProfile"],
      ["subject", "run<company-enrichment>"],
    ]);
    expect(program.environment[0]).toMatchObject({
      name: "SLACK_WEBHOOK_URL",
      required: true,
    });
    expect(program.effects.map((effect) => effect.kind)).toEqual([
      "read_external",
      "delivers",
    ]);
    expect(program.access.rules).toEqual({
      reads: ["company_private.leads"],
      callable_by: ["revenue", "admin"],
    });
    expect(program.execution?.body).toContain("call brief-writer");
    expect(ir.diagnostics).toEqual([]);
  });

  test("semantic hash ignores formatting-only blank line changes", () => {
    const a = compileFixture("whitespace-a.prose.md");
    const b = compileFixture("whitespace-b.prose.md");

    expect(a.semantic_hash).toBe(b.semantic_hash);
    expect(a.package.source_sha).not.toBe(b.package.source_sha);
  });

  test("semantic hash changes when port types change", () => {
    const source = fixture("whitespace-a.prose.md");
    const a = compileSource(source, { path: "fixtures/compiler/whitespace-a.prose.md" });
    const b = compileSource(source.replace("string - question", "number - question"), {
      path: "fixtures/compiler/whitespace-a.prose.md",
    });

    expect(a.semantic_hash).not.toBe(b.semantic_hash);
  });

  test("malformed source produces source-located diagnostics", () => {
    const ir = compileFixture("malformed.prose.md");

    expect(ir.diagnostics.map((diagnostic) => diagnostic.code)).toEqual([
      "malformed_port",
      "raw_execution_body",
    ]);
    expect(ir.diagnostics[0].source_span).toMatchObject({
      path: "fixtures/compiler/malformed.prose.md",
      start_line: 8,
      end_line: 8,
    });
  });

  test("projects a VM-readable manifest from IR", () => {
    const manifest = projectManifest(compileFixture("pipeline.prose.md"));

    expect(manifest).toContain("# Manifest: content-pipeline");
    expect(manifest).toContain("Generated by OpenProse from canonical IR.");
    expect(manifest).toContain("draft <- bindings/caller/draft.md");
    expect(manifest).toContain("feedback <- bindings/review/feedback.md");
    expect(manifest).toContain("claims <- bindings/fact-check/claims.md");
    expect(manifest).toContain("polish (depends on: fact-check, review)");
  });

  test("materializes a succeeded pure single-service run record", async () => {
    const runRoot = mkdtempSync(join(tmpdir(), "openprose-run-"));
    const result = await materializeSource(fixture("hello.prose.md"), {
      path: "fixtures/compiler/hello.prose.md",
      runRoot,
      runId: "20260423-120000-abc123",
      createdAt: "2026-04-23T12:00:00.000Z",
      outputs: {
        message: "Hello from a fixture output.",
      },
      trigger: "test",
    });
    const record = JSON.parse(readFileSync(join(result.run_dir, "run.json"), "utf8"));
    const output = readFileSync(
      join(result.run_dir, "bindings", "hello", "message.md"),
      "utf8",
    );

    expect(record).toMatchObject({
      run_id: "20260423-120000-abc123:hello",
      kind: "component",
      component_ref: "hello",
      status: "succeeded",
      acceptance: { status: "accepted" },
      runtime: { harness: "openprose-bun-local", worker_ref: "fixture-output" },
    });
    expect(output).toBe("Hello from a fixture output.\n");
  });

  test("materializes a graph run with node run records", async () => {
    const runRoot = mkdtempSync(join(tmpdir(), "openprose-graph-"));
    const result = await materializeSource(fixture("pipeline.prose.md"), {
      path: "fixtures/compiler/pipeline.prose.md",
      runRoot,
      runId: "20260423-121500-def456",
      createdAt: "2026-04-23T12:15:00.000Z",
      inputs: {
        draft: "The original draft.",
      },
      outputs: {
        "review.feedback": "Tighten the intro.",
        "fact-check.claims": "All claims verified.",
        "polish.final": "The polished draft.",
      },
      trigger: "test",
    });
    const record = JSON.parse(readFileSync(join(result.run_dir, "run.json"), "utf8"));

    expect(record).toMatchObject({
      run_id: "20260423-121500-def456",
      kind: "graph",
      component_ref: "content-pipeline",
      status: "succeeded",
    });
    expect(result.node_records.map((node) => [node.component_ref, node.status])).toEqual([
      ["review", "succeeded"],
      ["fact-check", "succeeded"],
      ["polish", "succeeded"],
    ]);
    expect(
      readFileSync(join(result.run_dir, "bindings", "$graph", "final.md"), "utf8"),
    ).toBe("The polished draft.\n");
  });

  test("materialization blocks missing fixture outputs", async () => {
    const runRoot = mkdtempSync(join(tmpdir(), "openprose-blocked-"));
    const result = await materializeSource(fixture("hello.prose.md"), {
      path: "fixtures/compiler/hello.prose.md",
      runRoot,
      runId: "20260423-123000-fed987",
      createdAt: "2026-04-23T12:30:00.000Z",
      trigger: "test",
    });

    expect(result.record.status).toBe("blocked");
    expect(result.record.acceptance).toMatchObject({
      status: "pending",
      reason: "Missing fixture output 'message'.",
    });
  });

  test("materialization blocks side-effecting graphs by default", async () => {
    const runRoot = mkdtempSync(join(tmpdir(), "openprose-effect-"));
    const result = await materializeSource(fixture("typed-effects.prose.md"), {
      path: "fixtures/compiler/typed-effects.prose.md",
      runRoot,
      runId: "20260423-124500-abc987",
      createdAt: "2026-04-23T12:45:00.000Z",
      inputs: {
        company: "Acme profile",
        subject: "run: prior-run",
      },
      outputs: {
        "brief-writer.brief": "Executive brief",
      },
      trigger: "test",
    });

    expect(result.record.status).toBe("blocked");
    expect(result.record.acceptance.reason).toContain(
      "Local materializer does not perform effect 'delivers'.",
    );
  });

  test("plans a pure graph as ready when caller inputs are available", () => {
    const plan = planSource(fixture("pipeline.prose.md"), {
      path: "fixtures/compiler/pipeline.prose.md",
      inputs: {
        draft: "The original draft.",
      },
    });

    expect(plan.status).toBe("ready");
    expect(plan.nodes.map((node) => [node.component_ref, node.status])).toEqual([
      ["review", "ready"],
      ["fact-check", "ready"],
      ["polish", "ready"],
    ]);
    expect(plan.nodes[0].stale_reasons).toEqual(["no_current_run"]);
  });

  test("plans missing caller inputs as blocked", () => {
    const plan = planSource(fixture("pipeline.prose.md"), {
      path: "fixtures/compiler/pipeline.prose.md",
    });

    expect(plan.status).toBe("blocked");
    expect(plan.nodes.map((node) => [node.component_ref, node.status])).toEqual([
      ["review", "blocked_input"],
      ["fact-check", "blocked_input"],
      ["polish", "blocked_input"],
    ]);
    expect(plan.nodes[0].blocked_reasons).toContain(
      "Missing required input 'draft'.",
    );
  });

  test("plans side-effecting graphs as blocked by effect", () => {
    const plan = planSource(fixture("typed-effects.prose.md"), {
      path: "fixtures/compiler/typed-effects.prose.md",
      inputs: {
        company: "Acme profile",
        subject: "run: prior-run",
      },
    });

    expect(plan.status).toBe("blocked");
    expect(plan.graph_blocked_reasons).toContain(
      "Graph effect 'delivers' requires a gate before execution.",
    );
    expect(plan.nodes).toContainEqual(
      expect.objectContaining({
        component_ref: "brief-writer",
        status: "ready",
      }),
    );
  });

  test("plans matching prior materialization as current", async () => {
    const runRoot = mkdtempSync(join(tmpdir(), "openprose-current-"));
    const materialized = await materializeSource(fixture("pipeline.prose.md"), {
      path: "fixtures/compiler/pipeline.prose.md",
      runRoot,
      runId: "20260423-131500-cur001",
      createdAt: "2026-04-23T13:15:00.000Z",
      inputs: {
        draft: "The original draft.",
      },
      outputs: {
        "review.feedback": "Tighten the intro.",
        "fact-check.claims": "All claims verified.",
        "polish.final": "The polished draft.",
      },
      trigger: "test",
    });

    const plan = planSource(fixture("pipeline.prose.md"), {
      path: "fixtures/compiler/pipeline.prose.md",
      inputs: {
        draft: "The original draft.",
      },
      currentRun: {
        graph: materialized.record,
        nodes: materialized.node_records,
      },
    });

    expect(plan.status).toBe("current");
    expect(plan.graph_stale_reasons).toEqual([]);
    expect(plan.nodes.map((node) => [node.component_ref, node.status])).toEqual([
      ["review", "current"],
      ["fact-check", "current"],
      ["polish", "current"],
    ]);
    expect(plan.nodes.every((node) => node.stale_reasons.length === 0)).toBe(true);
  });

  test("plans changed caller input as stale but ready", async () => {
    const runRoot = mkdtempSync(join(tmpdir(), "openprose-stale-input-"));
    const materialized = await materializeSource(fixture("pipeline.prose.md"), {
      path: "fixtures/compiler/pipeline.prose.md",
      runRoot,
      runId: "20260423-133000-sta001",
      createdAt: "2026-04-23T13:30:00.000Z",
      inputs: {
        draft: "The original draft.",
      },
      outputs: {
        "review.feedback": "Tighten the intro.",
        "fact-check.claims": "All claims verified.",
        "polish.final": "The polished draft.",
      },
      trigger: "test",
    });

    const plan = planSource(fixture("pipeline.prose.md"), {
      path: "fixtures/compiler/pipeline.prose.md",
      inputs: {
        draft: "A changed draft.",
      },
      currentRun: {
        graph: materialized.record,
        nodes: materialized.node_records,
      },
    });

    expect(plan.status).toBe("ready");
    expect(plan.graph_stale_reasons).toContain("input_hash_changed:draft");
    expect(plan.nodes[0].stale_reasons).toContain("input_hash_changed:draft");
    expect(plan.nodes[2].stale_reasons).toContain("upstream_stale:review");
  });

  test("plans changed source semantics as stale", async () => {
    const runRoot = mkdtempSync(join(tmpdir(), "openprose-stale-source-"));
    const materialized = await materializeSource(fixture("hello.prose.md"), {
      path: "fixtures/compiler/hello.prose.md",
      runRoot,
      runId: "20260423-134500-src001",
      createdAt: "2026-04-23T13:45:00.000Z",
      outputs: {
        message: "Hello from a fixture output.",
      },
      trigger: "test",
    });
    const changedSource = fixture("hello.prose.md").replace(
      "Markdown<Greeting>",
      "Markdown<NewGreeting>",
    );

    const plan = planSource(changedSource, {
      path: "fixtures/compiler/hello.prose.md",
      currentRun: {
        graph: null,
        nodes: materialized.node_records,
      },
    });

    expect(plan.status).toBe("ready");
    expect(plan.nodes[0].stale_reasons).toContain("ir_hash_changed");
  });
});
