import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { compileSource } from "../src/compiler";
import { projectManifest } from "../src/manifest";

function fixture(name: string): string {
  return readFileSync(new URL(`../fixtures/compiler/${name}`, import.meta.url), "utf8");
}

function compileFixture(name: string) {
  return compileSource(fixture(name), { path: `fixtures/compiler/${name}` });
}

describe("OpenProse compiler", () => {
  test("compiles a single service to IR", () => {
    const ir = compileFixture("hello.prose.md");

    expect(ir.ir_version).toBe("0.1");
    expect(ir.package.name).toBe("hello");
    expect(ir.components).toHaveLength(1);
    expect(ir.components[0].kind).toBe("service");
    expect(ir.components[0].ports.ensures[0]).toMatchObject({
      name: "message",
      type: "Markdown<Greeting>",
      direction: "output",
      required: true,
    });
    expect(ir.components[0].effects[0]).toMatchObject({ kind: "pure" });
    expect(ir.diagnostics).toEqual([]);
  });

  test("builds exact graph edges for inline pipeline components", () => {
    const ir = compileFixture("pipeline.prose.md");
    const edges = ir.graph.edges.map(
      (edge) =>
        `${edge.from.component}.${edge.from.port}->${edge.to.component}.${edge.to.port}`,
    );

    expect(ir.components.map((component) => component.id)).toEqual([
      "content-pipeline",
      "review",
      "fact-check",
      "polish",
    ]);
    expect(edges).toContain("$caller.draft->review.draft");
    expect(edges).toContain("$caller.draft->fact-check.draft");
    expect(edges).toContain("$caller.draft->polish.draft");
    expect(edges).toContain("review.feedback->polish.feedback");
    expect(edges).toContain("fact-check.claims->polish.claims");
    expect(edges).toContain("polish.final->$return.final");
    expect(ir.diagnostics).toEqual([]);
  });

  test("parses typed ports, run inputs, effects, access, environment, and execution", () => {
    const ir = compileFixture("typed-effects.prose.md");
    const program = ir.components[0];

    expect(program.ports.requires.map((port) => [port.name, port.type])).toEqual([
      ["company", "CompanyProfile"],
      ["subject", "run<company-enrichment>"],
    ]);
    expect(program.environment[0]).toMatchObject({
      name: "SLACK_WEBHOOK_URL",
      required: true,
    });
    expect(program.effects.map((effect) => effect.kind)).toEqual([
      "read_external",
      "delivers",
    ]);
    expect(program.access.rules).toEqual({
      reads: ["company_private.leads"],
      callable_by: ["revenue", "admin"],
    });
    expect(program.execution?.body).toContain("call brief-writer");
    expect(ir.diagnostics).toEqual([]);
  });

  test("semantic hash ignores formatting-only blank line changes", () => {
    const a = compileFixture("whitespace-a.prose.md");
    const b = compileFixture("whitespace-b.prose.md");

    expect(a.semantic_hash).toBe(b.semantic_hash);
    expect(a.package.source_sha).not.toBe(b.package.source_sha);
  });

  test("semantic hash changes when port types change", () => {
    const source = fixture("whitespace-a.prose.md");
    const a = compileSource(source, { path: "fixtures/compiler/whitespace-a.prose.md" });
    const b = compileSource(source.replace("string - question", "number - question"), {
      path: "fixtures/compiler/whitespace-a.prose.md",
    });

    expect(a.semantic_hash).not.toBe(b.semantic_hash);
  });

  test("malformed source produces source-located diagnostics", () => {
    const ir = compileFixture("malformed.prose.md");

    expect(ir.diagnostics.map((diagnostic) => diagnostic.code)).toEqual([
      "malformed_port",
      "raw_execution_body",
    ]);
    expect(ir.diagnostics[0].source_span).toMatchObject({
      path: "fixtures/compiler/malformed.prose.md",
      start_line: 8,
      end_line: 8,
    });
  });

  test("projects a VM-readable manifest from IR", () => {
    const manifest = projectManifest(compileFixture("pipeline.prose.md"));

    expect(manifest).toContain("# Manifest: content-pipeline");
    expect(manifest).toContain("Generated by OpenProse from canonical IR.");
    expect(manifest).toContain("draft <- bindings/caller/draft.md");
    expect(manifest).toContain("feedback <- bindings/review/feedback.md");
    expect(manifest).toContain("claims <- bindings/fact-check/claims.md");
    expect(manifest).toContain("polish (depends on: fact-check, review)");
  });
});
