import {
  buildArtifactManifest,
  buildRegistryRef,
  buildTextMateGrammar,
  compileFixture,
  compileSource,
  describe,
  executeRemoteFile,
  expect,
  fixture,
  fixturePath,
  formatPath,
  formatSource,
  graphSource,
  highlightSource,
  installRegistryRef,
  installWorkspaceDependencies,
  join,
  lintPath,
  lintSource,
  materializeSource,
  mkdirSync,
  mkdtempSync,
  packagePath,
  parseRegistryRef,
  planSource,
  preflightPath,
  projectManifest,
  publishCheckPath,
  readFileSync,
  renderCatalogSearchText,
  renderFormatCheckText,
  renderGraphMermaid,
  renderHighlightHtml,
  renderHighlightText,
  renderLintReportText,
  renderLintText,
  renderPackageText,
  renderPreflightText,
  renderPublishCheckText,
  renderStatusText,
  renderTextMateGrammar,
  renderTraceText,
  runGit,
  searchCatalog,
  statusPath,
  test,
  tmpdir,
  traceFile,
  writeFileSync,
} from "./support";

describe("OpenProse source tooling", () => {
  test("passes preflight when required environment and installed dependencies are present", async () => {
    const root = mkdtempSync(join(tmpdir(), "openprose-preflight-pass-"));
    mkdirSync(join(root, "services"), { recursive: true });
    mkdirSync(join(root, ".deps", "github.com", "openprose", "prose"), {
      recursive: true,
    });
    writeFileSync(
      join(root, "prose.lock"),
      "# prose.lock — pinned dependency versions\n# Generated by OpenProse\ngithub.com/openprose/prose abc12345\n",
    );
    writeFileSync(
      join(root, "program.prose.md"),
      `---
name: preflight-demo
kind: program
---

### Services

- worker

### Ensures

- \`report\`: Markdown<Report> - final report

### Dependencies

- use "std/delivery/slack-notifier"
`,
    );
    writeFileSync(
      join(root, "services", "worker.prose.md"),
      `---
name: worker
kind: service
---

### Ensures

- \`report\`: Markdown<Report> - final report

### Environment

- \`SLACK_WEBHOOK_URL\`: runtime delivery hook

### Effects

- \`read_external\`: reads delivery context
`,
    );

    const result = await preflightPath(join(root, "program.prose.md"), {
      environment: {
        SLACK_WEBHOOK_URL: "",
      },
    });
    const text = renderPreflightText(result);

    expect(result.status).toBe("pass");
    expect(result.component_refs).toEqual(["preflight-demo", "worker"]);
    expect(result.environment).toEqual([
      {
        name: "SLACK_WEBHOOK_URL",
        status: "set",
        declared_by: ["worker"],
      },
    ]);
    expect(result.dependencies).toEqual([
      expect.objectContaining({
        package: "github.com/openprose/prose",
        sha: "abc12345",
        pinned: true,
        installed: true,
      }),
    ]);
    expect(text).toContain("Preflight: PASS");
    expect(text).toContain("SLACK_WEBHOOK_URL: set");
  });

  test("fails preflight when environment or dependency installs are missing", async () => {
    const root = mkdtempSync(join(tmpdir(), "openprose-preflight-fail-"));
    writeFileSync(
      join(root, "program.prose.md"),
      `---
name: preflight-demo
kind: program
---

### Ensures

- \`report\`: Markdown<Report> - final report

### Environment

- \`EXA_API_KEY\`: search access

### Dependencies

- use "std/evals/inspector"
`,
    );

    const result = await preflightPath(join(root, "program.prose.md"), {
      environment: {},
    });

    expect(result.status).toBe("fail");
    expect(result.missing).toContain("Missing required environment variable 'EXA_API_KEY'.");
    expect(result.missing).toContain(
      "Dependency 'github.com/openprose/prose' is not pinned in prose.lock.",
    );
  });

  test("lints non-canonical source structure", () => {
    const source = `---
name: lint-me
kind: service
---

### Ensures

- \`report\`: Markdown<Report> - final report

### Requires

- \`input\`: string - source input

### Execution

let result = call worker
  input: input

return result
`;

    const diagnostics = lintSource(source, {
      path: "fixtures/compiler/lint-me.md",
    });
    const text = renderLintText(diagnostics);

    expect(diagnostics.map((diagnostic) => diagnostic.code)).toEqual([
      "non_canonical_extension",
      "non_canonical_section_order",
      "raw_execution_body",
    ]);
    expect(text).toContain("non_canonical_extension");
    expect(text).toContain("non_canonical_section_order");
    expect(text).toContain("raw_execution_body");
  });

  test("formats supported source into canonical order and fenced execution", () => {
    const source = `---
kind: service
name: tidy-me
---

### Ensures

- \`report\`: Markdown<Report> - final report

### Requires

- \`input\`: string - source input

### Execution

let result = call worker
  input: input

return result
`;

    const formatted = formatSource(source, {
      path: "fixtures/compiler/tidy-me.prose.md",
    });

    expect(formatted).toContain("name: tidy-me\nkind: service");
    expect(formatted.indexOf("### Requires")).toBeLessThan(
      formatted.indexOf("### Ensures"),
    );
    expect(formatted).toContain("```prose");
    expect(formatted).toContain("return result");
  });

  test("formatting keeps the semantic hash stable", () => {
    const source = `---
kind: service
name: stable-format
---

### Ensures

- \`report\`: Markdown<Report> - final report

### Requires

- \`input\`: string - source input
`;

    const formatted = formatSource(source, {
      path: "fixtures/compiler/stable-format.prose.md",
    });
    const before = compileSource(source, {
      path: "fixtures/compiler/stable-format.prose.md",
    });
    const after = compileSource(formatted, {
      path: "fixtures/compiler/stable-format.prose.md",
    });

    expect(before.semantic_hash).toBe(after.semantic_hash);
  });

  test("highlights canonical source tokens", () => {
    const view = highlightSource(
      fixture("typed-effects.prose.md"),
      "fixtures/compiler/typed-effects.prose.md",
    );
    const scopes = view.tokens.map((token) => [token.scope, token.text]);

    expect(scopes).toContainEqual(["frontmatter.key", "name"]);
    expect(scopes).toContainEqual(["component.kind", "program"]);
    expect(scopes).toContainEqual(["section.header", "Requires"]);
    expect(scopes).toContainEqual(["port.name", "company"]);
    expect(scopes).toContainEqual(["port.type", "CompanyProfile"]);
    expect(scopes).toContainEqual(["env.name", "SLACK_WEBHOOK_URL"]);
    expect(scopes).toContainEqual(["effect.kind", "read_external"]);
    expect(scopes).toContainEqual(["access.label", "company_private.leads"]);
    expect(scopes).toContainEqual(["prose.keyword", "call"]);
    expect(scopes).toContainEqual(["prose.call_target", "brief-writer"]);
    expect(scopes).toContainEqual(["prose.keyword", "return"]);
  });

  test("renders highlight tokens as text", () => {
    const text = renderHighlightText(
      highlightSource(fixture("hello.prose.md"), "fixtures/compiler/hello.prose.md"),
    );

    expect(text).toContain("frontmatter.key: name");
    expect(text).toContain("component.kind: service");
    expect(text).toContain("section.header: Ensures");
    expect(text).toContain("port.name: message");
  });

  test("renders highlight tokens as html preview", () => {
    const source = fixture("typed-effects.prose.md");
    const html = renderHighlightHtml(
      source,
      highlightSource(source, "fixtures/compiler/typed-effects.prose.md"),
    );

    expect(html).toContain("<!doctype html>");
    expect(html).toContain("OpenProse Highlight Preview");
    expect(html).toContain('class="scope-frontmatter-key">name</span>');
    expect(html).toContain('class="scope-port-type">CompanyProfile</span>');
    expect(html).toContain('class="scope-effect-kind">read_external</span>');
    expect(html).toContain('class="scope-prose-call-target">brief-writer</span>');
  });

  test("builds a textmate grammar artifact", () => {
    const grammar = buildTextMateGrammar();
    const text = renderTextMateGrammar();
    const artifact = readFileSync(
      new URL("../syntaxes/openprose.tmLanguage.json", import.meta.url),
      "utf8",
    );

    expect(grammar.scopeName).toBe("text.openprose.markdown");
    expect(grammar.fileTypes).toContain("prose.md");
    expect(text).toContain('"storage.type.component-kind.openprose"');
    expect(text).toContain('"entity.name.function.call-target.openprose"');
    expect(text).toContain('"variable.parameter.port.openprose"');
    expect(artifact).toBe(text);
  });

  test("lints a directory of source files", async () => {
    const dir = mkdtempSync(join(tmpdir(), "openprose-lint-dir-"));
    writeFileSync(
      join(dir, "legacy.md"),
      `---
name: legacy
kind: service
---

### Ensures

- \`report\`: Markdown<Report> - final report

### Requires

- \`input\`: string - source input
`,
    );
    writeFileSync(
      join(dir, "clean.prose.md"),
      fixture("hello.prose.md"),
    );
    writeFileSync(
      join(dir, "README.md"),
      "# Package Docs\n\nThis is ordinary documentation, not executable source.\n",
    );

    const report = await lintPath(dir);
    const text = renderLintReportText(report);

    expect(Array.from(report.keys()).length).toBe(2);
    expect(report.get(join(dir, "legacy.md").replace(/\\/g, "/"))?.map((d) => d.code)).toContain(
      "non_canonical_extension",
    );
    expect(text).toContain("legacy.md: 2 diagnostics");
    expect(text).toContain("clean.prose.md: 0 diagnostics");
  });

  test("lints a directory with package-local service references", async () => {
    const dir = mkdtempSync(join(tmpdir(), "openprose-lint-package-"));
    writeFileSync(
      join(dir, "pipeline.prose.md"),
      `---
name: package-pipeline
kind: program
---

### Services

- \`summarize\`

### Ensures

- \`brief\`: Markdown<Brief> - package brief
`,
    );
    writeFileSync(
      join(dir, "summarize.prose.md"),
      `---
name: summarize
kind: service
---

### Ensures

- \`brief\`: Markdown<Brief> - package brief

### Effects

- \`pure\`: deterministic synthesis over provided inputs
`,
    );

    const report = await lintPath(dir);

    expect(
      report
        .get(join(dir, "pipeline.prose.md").replace(/\\/g, "/"))
        ?.map((diagnostic) => diagnostic.code),
    ).toEqual([]);
    expect(
      report
        .get(join(dir, "summarize.prose.md").replace(/\\/g, "/"))
        ?.map((diagnostic) => diagnostic.code),
    ).toEqual([]);
  });

  test("does not resolve service references from ordinary markdown headings", async () => {
    const dir = mkdtempSync(join(tmpdir(), "openprose-lint-doc-headings-"));
    writeFileSync(
      join(dir, "pipeline.prose.md"),
      `---
name: package-pipeline
kind: program
---

### Services

- \`docs-only-helper\`

### Ensures

- \`brief\`: Markdown<Brief> - package brief
`,
    );
    writeFileSync(
      join(dir, "README.md"),
      "# Package Docs\n\n## docs-only-helper\n\nThis is documentation, not a component.\n",
    );

    const report = await lintPath(dir);

    expect(Array.from(report.keys())).toEqual([
      join(dir, "pipeline.prose.md").replace(/\\/g, "/"),
    ]);
    expect(
      report
        .get(join(dir, "pipeline.prose.md").replace(/\\/g, "/"))
        ?.map((diagnostic) => diagnostic.code),
    ).toEqual(["unresolved_service_reference"]);
  });

  test("lints a package subdirectory with package-wide service context", async () => {
    const dir = mkdtempSync(join(tmpdir(), "openprose-lint-scope-"));
    const systemsDir = join(dir, "systems");
    const sharedDir = join(dir, "shared");
    mkdirSync(systemsDir, { recursive: true });
    mkdirSync(sharedDir, { recursive: true });
    writeFileSync(
      join(dir, "prose.package.json"),
      JSON.stringify(
        {
          name: "@openprose/lint-scope",
          version: "0.1.0",
          registry: {
            catalog: "openprose",
          },
        },
        null,
        2,
      ),
    );
    writeFileSync(
      join(systemsDir, "pipeline.prose.md"),
      `---
name: package-pipeline
kind: program
---

### Services

- \`summarize\`

### Ensures

- \`brief\`: Markdown<Brief> - package brief
`,
    );
    writeFileSync(
      join(sharedDir, "summarize.prose.md"),
      `---
name: summarize
kind: service
---

### Ensures

- \`brief\`: Markdown<Brief> - package brief

### Effects

- \`pure\`: deterministic synthesis over provided inputs
`,
    );

    const report = await lintPath(systemsDir);

    expect(
      report
        .get(join(systemsDir, "pipeline.prose.md").replace(/\\/g, "/"))
        ?.map((diagnostic) => diagnostic.code),
    ).toEqual([]);
  });

  test("checks formatting across a directory of canonical files", async () => {
    const dir = mkdtempSync(join(tmpdir(), "openprose-fmt-dir-"));
    const tidyPath = join(dir, "tidy.prose.md");
    const cleanPath = join(dir, "clean.prose.md");
    writeFileSync(
      tidyPath,
      `---
kind: service
name: tidy
---

### Ensures

- \`report\`: Markdown<Report> - final report

### Requires

- \`input\`: string - source input
`,
    );
    writeFileSync(
      cleanPath,
      formatSource(fixture("hello.prose.md"), { path: cleanPath }),
    );

    const results = await formatPath(dir, { check: true });
    const text = renderFormatCheckText(results);

    expect(results).toContainEqual({
      path: tidyPath.replace(/\\/g, "/"),
      changed: true,
    });
    expect(results).toContainEqual({
      path: cleanPath.replace(/\\/g, "/"),
      changed: false,
    });
    expect(text).toContain("Needs formatting");
    expect(text).toContain("tidy.prose.md");
  });
});
