#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path

SKIP_NAMES = {
    "README.md",
    "CHANGELOG.md",
    "LICENSE",
    "TERMS.md",
    "PRIVACY.md",
    "CONTRIBUTING.md",
}


def add_alias(aliases: dict[str, str], key: str, path: Path) -> None:
    aliases.setdefault(key, str(path.resolve()))


def looks_program_like(path: Path) -> bool:
    if path.name in SKIP_NAMES:
        return False
    if path.suffix == ".prose":
        return True
    if path.name == "SKILL.md":
        return True
    if path.suffix != ".md":
        return False

    try:
        head = path.read_text(encoding="utf-8", errors="ignore")[:2048]
    except OSError:
        return False

    if head.startswith("---"):
        return True
    if "kind: program" in head or "kind: service" in head or "services:" in head:
        return True
    if "/examples/" in path.as_posix():
        return True
    return False


def build_aliases(root: Path) -> dict[str, str]:
    aliases: dict[str, str] = {}

    for path in root.rglob("*"):
        if not path.is_file() or not looks_program_like(path):
            continue

        rel = path.relative_to(root).as_posix()
        stem = path.stem

        add_alias(aliases, rel, path)
        add_alias(aliases, path.name, path)

        if path.suffix == ".prose":
            add_alias(aliases, stem, path)
        elif path.name.endswith(".prose.md"):
            add_alias(aliases, path.name[:-3], path)
            add_alias(aliases, path.name[:-9], path)
        elif path.name == "index.md":
            add_alias(aliases, path.parent.name, path)
            add_alias(aliases, path.parent.relative_to(root).as_posix(), path)
        elif path.name == "SKILL.md":
            add_alias(aliases, path.parent.name, path)
        else:
            add_alias(aliases, stem, path)

    return aliases


def write_toml(aliases: dict[str, str], out: Path) -> None:
    lines = [
        "# Generated by build_aliases.py",
        "# Review before use if your repo contains overlapping names.",
        "",
        "[aliases]",
    ]

    for key in sorted(aliases):
        value = aliases[key].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'"{key}" = "{value}"')

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a local alias registry for OpenProse workflows and skills."
    )
    parser.add_argument("--root", required=True, help="Repository root to scan")
    parser.add_argument("--out", required=True, help="Output TOML path")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    out = Path(args.out).resolve()

    aliases = build_aliases(root)
    write_toml(aliases, out)

    print(f"Wrote {len(aliases)} aliases to {out}")


if __name__ == "__main__":
    main()
