# frozen_string_literal: true

# Generated by cli/homebrew/generate_formula.rb.
# Replace url and sha256 with the release tarball values before publishing.

class OpenproseCli < Formula
  desc "Run OpenProse commands through Codex, Claude, or SDK-backed agent harnesses"
  homepage "https://github.com/openprose/prose"
  url "https://github.com/openprose/prose/releases/download/prose-cli-v0.1.0/openprose-prose-cli-0.1.0-homebrew.tgz"
  version "0.1.0"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  depends_on "node"

  def install
    cp "package-lock.json", "npm-shrinkwrap.json" if File.exist?("package-lock.json")
    system "npm", "install", *std_npm_args
    (bin/"prose").write_env_script libexec/"bin/prose", PATH: "#{Formula["node"].opt_bin}:$PATH"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/prose --version")
    assert_match "Usage:", shell_output("#{bin}/prose --help")
  end
end
