import { existsSync, readFileSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

export interface RegistryLockPin {
  ref: string;
  package: string;
  sha: string;
}

export interface LockfileData {
  path: string;
  source_pins: Map<string, string>;
  registry_pins: Map<string, RegistryLockPin>;
}

export async function loadLockfile(path: string): Promise<LockfileData> {
  const filePath = resolve(path);
  if (!existsSync(filePath)) {
    return {
      path: filePath,
      source_pins: new Map(),
      registry_pins: new Map(),
    };
  }

  return parseLockfile(await readFile(filePath, "utf8"), filePath);
}

export async function findNearestLockfile(path: string): Promise<LockfileData | null> {
  return findNearestLockfileSync(path);
}

export function findNearestLockfileSync(path: string): LockfileData | null {
  let current = dirname(resolve(path));

  while (true) {
    const candidate = resolve(current, "prose.lock");
    if (existsSync(candidate)) {
      return parseLockfile(readFileSync(candidate, "utf8"), candidate);
    }

    const parent = dirname(current);
    if (parent === current) {
      return null;
    }
    current = parent;
  }
}

export async function writeLockfile(lockfile: LockfileData): Promise<void> {
  const lines = [
    "# prose.lock — pinned dependency versions",
    "# Generated by OpenProse",
  ];

  for (const [pkg, sha] of Array.from(lockfile.source_pins.entries()).sort(([a], [b]) =>
    a.localeCompare(b),
  )) {
    lines.push(`${pkg} ${sha}`);
  }

  for (const pin of Array.from(lockfile.registry_pins.values()).sort((a, b) =>
    a.ref.localeCompare(b.ref),
  )) {
    lines.push(`${pin.ref} ${pin.package} ${pin.sha}`);
  }

  await writeFile(lockfile.path, `${lines.join("\n")}\n`, "utf8");
}

export function parseLockfile(source: string, path = "prose.lock"): LockfileData {
  const data: LockfileData = {
    path: resolve(path),
    source_pins: new Map(),
    registry_pins: new Map(),
  };

  for (const rawLine of source.replace(/\r\n/g, "\n").split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }

    const parts = line.split(/\s+/);
    if (parts.length === 2 && !parts[0].startsWith("registry://")) {
      data.source_pins.set(parts[0], parts[1]);
      continue;
    }

    if (parts.length === 3 && parts[0].startsWith("registry://")) {
      data.registry_pins.set(parts[0], {
        ref: parts[0],
        package: parts[1],
        sha: parts[2],
      });
    }
  }

  return data;
}
