import type { ComponentIR, GraphEdgeIR, ProseIR } from "./types";

export function projectManifest(ir: ProseIR): string {
  const main = ir.components.find((component) => component.kind === "program");
  const executable = getExecutableComponents(ir.components, main);
  const lines: string[] = [];

  lines.push(`# Manifest: ${main?.name ?? ir.components[0]?.name ?? ir.package.name}`);
  lines.push("");
  lines.push("Generated by OpenProse from canonical IR.");
  lines.push(`Source: ${ir.package.source_ref}`);
  lines.push(`IR Hash: ${ir.semantic_hash}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Caller Interface");
  lines.push("");
  lines.push("requires:");
  for (const port of (main ?? ir.components[0])?.ports.requires ?? []) {
    const type = port.type === "Any" ? "" : `${port.type} - `;
    lines.push(`- ${port.name} (from user): ${type}${port.description}`);
  }
  if (((main ?? ir.components[0])?.ports.requires ?? []).length === 0) {
    lines.push("- (none)");
  }
  lines.push("");
  lines.push("returns:");
  for (const port of (main ?? ir.components[0])?.ports.ensures ?? []) {
    const provider = findReturnProvider(ir.graph.edges, port.name);
    const from = provider ? `from ${provider}` : "from component";
    const type = port.type === "Any" ? "" : `${port.type} - `;
    lines.push(`- ${port.name} (${from}): ${type}${port.description}`);
  }
  if (((main ?? ir.components[0])?.ports.ensures ?? []).length === 0) {
    lines.push("- (none)");
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Graph");

  for (const component of executable) {
    lines.push("");
    lines.push(`### ${component.name}`);
    lines.push("");
    lines.push(`source: ${component.source.path}`);
    lines.push(`workspace: workspace/${component.id}/`);
    lines.push("");
    lines.push("inputs:");
    const inputLines = component.ports.requires.map((port) =>
      formatInputMapping(ir.graph.edges, component, port.name),
    );
    if (inputLines.length === 0) {
      lines.push("  (none)");
    } else {
      lines.push(...inputLines);
    }
    lines.push("");
    lines.push("outputs:");
    if (component.ports.ensures.length === 0) {
      lines.push("  (none)");
    } else {
      for (const port of component.ports.ensures) {
        lines.push(
          `  ${port.name} -> workspace/${component.id}/${port.name}.md`,
        );
        lines.push(
          `  (public) ${port.name} -> bindings/${component.id}/${port.name}.md`,
        );
      }
    }
  }

  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Execution Order");
  lines.push("");

  const ordered = topologicalOrder(executable, ir.graph.edges);
  if (ordered.length === 0) {
    lines.push("1. (none)");
  } else {
    ordered.forEach((component, index) => {
      const deps = dependenciesFor(component.id, ir.graph.edges);
      lines.push(
        `${index + 1}. ${component.name} (depends on: ${
          deps.length ? deps.join(", ") : "caller"
        })`,
      );
    });
  }

  const parallelizable = executable
    .filter((component) => dependenciesFor(component.id, ir.graph.edges).length === 0)
    .map((component) => component.name);
  lines.push("");
  lines.push(
    `Parallelizable: ${parallelizable.length ? parallelizable.join(", ") : "(none)"}`,
  );

  const environment = collectEnvironment(ir.components);
  if (environment.size > 0) {
    lines.push("");
    lines.push("## Environment");
    lines.push("");
    lines.push("| Variable | Required by |");
    lines.push("| --- | --- |");
    for (const [name, requiredBy] of environment.entries()) {
      lines.push(`| ${name} | ${Array.from(requiredBy).join(", ")} |`);
    }
  }

  const warnings = ir.diagnostics.filter(
    (diagnostic) => diagnostic.severity !== "info",
  );
  if (warnings.length > 0) {
    lines.push("");
    lines.push("## Warnings");
    lines.push("");
    for (const warning of warnings) {
      const location = warning.source_span
        ? ` (${warning.source_span.path}:${warning.source_span.start_line})`
        : "";
      lines.push(`- [${warning.severity}] ${warning.code}${location}: ${warning.message}`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function getExecutableComponents(
  components: ComponentIR[],
  main: ComponentIR | undefined,
): ComponentIR[] {
  if (main && components.length > 1) {
    return components.filter((component) => component.id !== main.id);
  }
  return components;
}

function formatInputMapping(
  edges: GraphEdgeIR[],
  component: ComponentIR,
  portName: string,
): string {
  const edge = edges.find(
    (candidate) =>
      candidate.to.component === component.id && candidate.to.port === portName,
  );

  if (!edge) {
    return `  ${portName} <- (unresolved)`;
  }

  if (edge.from.component === "$caller") {
    return `  ${portName} <- bindings/caller/${edge.from.port}.md`;
  }

  return `  ${portName} <- bindings/${edge.from.component}/${edge.from.port}.md`;
}

function findReturnProvider(edges: GraphEdgeIR[], portName: string): string | null {
  const edge = edges.find(
    (candidate) =>
      candidate.to.component === "$return" && candidate.to.port === portName,
  );
  return edge?.from.component ?? null;
}

function topologicalOrder(
  components: ComponentIR[],
  edges: GraphEdgeIR[],
): ComponentIR[] {
  const byId = new Map(components.map((component) => [component.id, component]));
  const dependencies = new Map<string, Set<string>>();
  for (const component of components) {
    dependencies.set(component.id, new Set());
  }

  for (const edge of edges) {
    if (!byId.has(edge.to.component) || !byId.has(edge.from.component)) {
      continue;
    }
    dependencies.get(edge.to.component)?.add(edge.from.component);
  }

  const ordered: ComponentIR[] = [];
  const remaining = new Set(components.map((component) => component.id));

  while (remaining.size > 0) {
    const ready = Array.from(remaining).filter((id) => {
      const deps = dependencies.get(id) ?? new Set<string>();
      return Array.from(deps).every((dep) => !remaining.has(dep));
    });

    if (ready.length === 0) {
      return components;
    }

    ready.sort();
    for (const id of ready) {
      const component = byId.get(id);
      if (component) {
        ordered.push(component);
      }
      remaining.delete(id);
    }
  }

  return ordered;
}

function dependenciesFor(componentId: string, edges: GraphEdgeIR[]): string[] {
  return Array.from(
    new Set(
      edges
        .filter(
          (edge) =>
            edge.to.component === componentId &&
            edge.from.component !== "$caller" &&
            edge.from.component !== "$return",
        )
        .map((edge) => edge.from.component),
    ),
  ).sort();
}

function collectEnvironment(components: ComponentIR[]): Map<string, Set<string>> {
  const environment = new Map<string, Set<string>>();
  for (const component of components) {
    for (const variable of component.environment) {
      const requiredBy = environment.get(variable.name) ?? new Set<string>();
      requiredBy.add(component.name);
      environment.set(variable.name, requiredBy);
    }
  }
  return environment;
}

