#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "optparse"
require "pathname"

ROOT = Pathname.new(__dir__).parent
PACKAGE_JSON = ROOT/"package.json"
DEFAULT_FORMULA_NAME = "openprose-cli"
DEFAULT_OUTPUT = Pathname.new(__dir__)/"Formula"/"#{DEFAULT_FORMULA_NAME}.rb"
PLACEHOLDER_SHA256 = "0" * 64

package = JSON.parse(PACKAGE_JSON.read)

def formula_class_name(name)
  name.split(/[^A-Za-z0-9]+/).reject(&:empty?).map(&:capitalize).join
end

def homebrew_tarball_url(version)
  "https://github.com/openprose/prose/releases/download/prose-cli-v#{version}/openprose-prose-cli-#{version}-homebrew.tgz"
end

options = {
  desc: package.fetch("description").sub(/\.+\z/, ""),
  formula_name: DEFAULT_FORMULA_NAME,
  homepage: "https://github.com/openprose/prose",
  license: package.fetch("license"),
  output: DEFAULT_OUTPUT.to_s,
  sha256: PLACEHOLDER_SHA256,
  version: package.fetch("version"),
}

OptionParser.new do |parser|
  parser.banner = "Usage: ruby cli/homebrew/generate_formula.rb [options]"

  parser.on("--version VERSION", "Package version to write into the formula.") do |value|
    options[:version] = value
  end

  parser.on("--url URL", "Release tarball URL. Defaults to the Homebrew release asset pattern.") do |value|
    options[:url] = value
  end

  parser.on("--sha256 SHA256", "Release tarball SHA-256. Defaults to a placeholder.") do |value|
    options[:sha256] = value
  end

  parser.on("--homepage URL", "Project homepage for the formula.") do |value|
    options[:homepage] = value
  end

  parser.on("--formula-name NAME", "Formula file/class base name. Defaults to openprose-cli.") do |value|
    options[:formula_name] = value
  end

  parser.on("--output PATH", "Formula output path. Defaults to cli/homebrew/Formula/openprose-cli.rb.") do |value|
    options[:output] = value
  end

  parser.on("-h", "--help", "Print this help.") do
    puts parser
    exit
  end
end.parse!

options[:url] ||= homebrew_tarball_url(options[:version])
class_name = formula_class_name(options[:formula_name])

formula = <<~RUBY
  # frozen_string_literal: true

  # Generated by cli/homebrew/generate_formula.rb.
  # Replace url and sha256 with the release tarball values before publishing.

  class #{class_name} < Formula
    desc #{options[:desc].inspect}
    homepage #{options[:homepage].inspect}
    url #{options[:url].inspect}
    version #{options[:version].inspect}
    sha256 #{options[:sha256].inspect}
    license #{options[:license].inspect}

    depends_on "node"

    def install
      cp "package-lock.json", "npm-shrinkwrap.json" if File.exist?("package-lock.json")
      system "npm", "install", *std_npm_args
      (bin/"prose").write_env_script libexec/"bin/prose", PATH: "\#{Formula["node"].opt_bin}:$PATH"
    end

    test do
      assert_match version.to_s, shell_output("\#{bin}/prose --version")
      assert_match "Usage:", shell_output("\#{bin}/prose --help")
    end
  end
RUBY

output = Pathname.new(options[:output])
output.dirname.mkpath
output.write(formula)
puts "Wrote #{output}"
